[project]
name = "mojo-learn"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sean Toner <placeoftheway@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]

[tasks]


[dependencies]
python = ">=3.12"
pydantic = ">=2.6.4,<2.7"

[feature.test.dependencies]
autopep8 = ">=1.3.2,<2.2"
ruff = ">=0.3.5,<0.4"
pytest = ">=7.2.0,<8.2"
pytest-asyncio = ">=0.14.0,<0.24"

[feature.data.dependencies]
polars = ">=0.20.18,<0.21"
pyarrow = ">=15.0.2,<15.1"

[feature.viz.dependencies]
jupyterlab = ">=1.0.10,<4.2"
ipykernel = ">=6.14.0,<6.30"
ipywidgets = ">=7.3.0,<8.2"
plotly = ">=2.7.0,<5.20"

[feature.serve.dependencies]
fastapi = ">=0.110.1,<0.111"
uvicorn = ">=0.29.0,<0.30"

[feature.cuda]
channels = ["nvidia"]
platforms = ["linux-64","win-64"]
system-requirements = {cuda = "12"}
pypi-dependencies = { torch = "*" }

[environments]
test = ["test"]
data = ["data"]
viz = ["data", "viz"]
serve = ["data", "serve"]
cuda = ["cuda", "data"]

[build-dependencies]
rust = ">=1.77.1,<1.78"
clang = ">=18.1.3,<18.2"

[target.linux-64.tasks]
mod_ins = "curl -s https://get.modular.com | sh -"
mod_clean = "modular clean"
mojo_rem = "modular uninstall mojo"
mod_auth = { cmd = "modular auth", depends_on = ["mod_ins"] }
mojo_ins = { cmd = "modular install mojo", depends_on = ["mod_auth"] }

[target.osx-arm64.tasks]
mod_ins = "curl -s https://get.modular.com | sh -"
mod_clean = "modular clean"
mojo_rem = "modular uninstall mojo"
mod_auth = { cmd = "modular auth", depends_on = ["mod_ins"] }
mojo_ins = { cmd = "modular install mojo", depends_on = ["mod_auth"] }

