[project]
name = "mojo-learn"
version = "0.1.0"
description = "Project to learn mojo"
authors = ["Sean Toner <placeoftheway@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]
modular_ins = "curl -s https://get.modular.com | sh -"
mojo_ins = "modular install mojo"
mojo_upd = "modular update mojo"
mojo_del = "modular uninstall mojo"
modular_clean = "modular clean"

[dependencies]
python = ">=3.12.2,<3.13"
jupyter = ">=1.0.0,<1.1"
polars = ">=0.20.18,<0.21"
fastapi = ">=0.103.0,<0.104"

[host-dependencies]
pytest = ">=8.1.1,<8.2"
ruff = ">=0.3.5,<0.4"
autopep8 = ">=2.1.0,<2.2"

[build-dependencies]
rust = ">=1.77.1,<1.78"
clang = ">=18.1.2,<18.2"
cmake = ">=3.29.1,<3.30"

[pypi-dependencies]
coconut = "*"
daak = "*"
